### ISSUE TITLE
Most recent conda-forge lapackpp version not compatible with recent WarpX releases

### ISSUE THREAD

**Issue by plasmahomie** [BLAST-WarpX/warpx#7256]
## Description
The latest version of lapackpp available on conda-forge is 2022.05.00, which depends on blaspp version 2022.05.00, so if you just use conda install -c conda-forge lapackpp, etc (as is the instruction in the docs) you will have these versions. However (as I understand at least) there was a change to how blas APIs work in v2024.05.31 that broke its use in HankelTransform.cpp, and was fixed in WarpX 2024.06 as described in issue #5012, meaning that since this release WarpX RZ geometry is not compatible with a conda-forge installed environment. Below I list the output of trying to build WarpX in RZ geometry with spectral solvers, with the crucial error in trying to compile HankelTransform.cpp being:
/users/rnr512/my-warpx/warpx/Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp(38): error: class 
```
"blas::Queue" has no member "stream_t"
      blas::Queue::stream_t stream_id = amrex::Gpu::gpuStream();
                   ^

/users/rnr512/my-warpx/warpx/Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp(200): error: class "blas::Queue" has no member "stream_t"
      blas::Queue::stream_t stream_id = amrex::Gpu::gpuStream();
                   ^

/users/rnr512/my-warpx/warpx/Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp(201): error: class "blas::Queue" has no member "set_stream"
      m_queue->set_stream(stream_id);
               ^

/users/rnr512/my-warpx/warpx/Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp(235): error: class "blas::Queue" has no member "stream_t"
      blas::Queue::stream_t stream_id = amrex::Gpu::gpuStream();
                   ^

/users/rnr512/my-warpx/warpx/Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp(236): error: class "blas::Queue" has no member "set_stream"
      m_queue->set_stream(stream_id);
```

How do you recommend getting around this? Installing lapackpp from another source? I'd rather have everything from the same source. Or downgrading to an earlier WarpX version? Whatever the solution the installation instructions should be updated.

## System information
- Operating system (name and version):
  - [X] Linux: Rocky Linux 8.10
- Version of WarpX: latest, 26.09
- Installation method:
  - [X] From source with CMake on HPC cluster
- Other dependencies: Installed dependencies using conda, via command:
`conda create -n warpx blaspp boost ccache cmake compilers git lapackpp "openpmd-api=*=mpi_mpich*" openpmd-viewer packaging pytest python python-build make numpy pandas scipy setuptools yt "fftw=*=mpi_mpich*" pkg-config matplotlib mamba mpich mpi4py ninja pip virtualenv wheel cuda-version=13.2 cuda cuda-nvtx-dev cupy`
Resulting environment:
```
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                      20_gnu    conda-forge
adios2                    2.10.2          mpi_mpich_py39h8df973f_1    conda-forge
alsa-lib                  1.2.16.1             h7cc23a3_1    conda-forge
anyio                     4.10.0             pyhe01879c_0    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      25.1.0           py39hd399759_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attrs                     25.3.0             pyh71513ae_0    conda-forge
babel                     2.17.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.13.4             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.46.1          default_hfdba357_102    conda-forge
binutils_linux-64         2.46.1          default_h4852527_102    conda-forge
blaspp                    2022.05.00           hef2b0f7_0    conda-forge
bleach                    6.2.0              pyh29332c3_4    conda-forge
bleach-with-css           6.2.0                h82add2a_4    conda-forge
boost                     1.85.0               he8689d4_4    conda-forge
brotli-python             1.1.0            py39hf88036b_3    conda-forge
bzip2                     1.0.8               hda65f42_10    conda-forge
c-ares                    1.34.8               hebe6cf0_2    conda-forge
c-blosc2                  2.15.2               h3122c55_1    conda-forge
c-compiler                2.0.0                ha29393d_0    conda-forge
ca-certificates           2026.7.22            hbd8a1cb_0    conda-forge
cached-property           1.5.2                hd8ed1ab_2    conda-forge
cached_property           1.5.2              pyha770c72_2    conda-forge
ccache                    4.14                 h420ae53_0    conda-forge
certifi                   2025.8.3           pyhd8ed1ab_0    conda-forge
cffi                      1.17.1           py39h15c3d72_0    conda-forge
charset-normalizer        3.4.3              pyhd8ed1ab_0    conda-forge
cmake                     4.4.3                hff7ac6b_0    conda-forge
cmyt                      1.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
colorspacious             1.1.2              pyhecae5ae_1    conda-forge
comm                      0.2.3              pyhe01879c_0    conda-forge
compilers                 2.0.0                ha770c72_0    conda-forge
conda-gcc-specs           15.3.0               h8846f6e_4    conda-forge
cpp-expected              1.3.1                h171cf75_1    conda-forge
cpython                   3.9.23           py39hd8ed1ab_0    conda-forge
cuda                      13.2.2               ha804496_0    conda-forge
cuda-cccl_linux-64        13.2.86              ha770c72_0    conda-forge
cuda-command-line-tools   13.2.2               ha770c72_0    conda-forge
cuda-compiler             13.2.2               hbad6d8a_0    conda-forge
cuda-crt-dev_linux-64     13.2.86              ha770c72_0    conda-forge
cuda-crt-tools            13.2.86              ha770c72_0    conda-forge
cuda-ctadvisor            13.2.86              h676940d_0    conda-forge
cuda-cudart               13.2.86              hecca717_0    conda-forge
cuda-cudart-dev           13.2.86              hecca717_0    conda-forge
cuda-cudart-dev_linux-64  13.2.86              h376f20c_0    conda-forge
cuda-cudart-static        13.2.86              hecca717_0    conda-forge
cuda-cudart-static_linux-64 13.2.86              h376f20c_0    conda-forge
cuda-cudart_linux-64      13.2.86              h376f20c_0    conda-forge
cuda-cuobjdump            13.2.86              hffce074_0    conda-forge
cuda-cupti                13.2.86              h676940d_1    conda-forge
cuda-cupti-dev            13.2.86              h676940d_1    conda-forge
cuda-cuxxfilt             13.2.86              hffce074_0    conda-forge
cuda-driver-dev           13.2.86              hecca717_0    conda-forge
cuda-driver-dev_linux-64  13.2.86              h376f20c_0    conda-forge
cuda-gdb                  13.2.86              hba53cbc_0    conda-forge
cuda-libraries            13.2.2               ha770c72_0    conda-forge
cuda-libraries-dev        13.2.2               ha770c72_0    conda-forge
cuda-nsight               13.2.86              h7938cbb_0    conda-forge
cuda-nvcc                 13.2.86              hcdd1206_0    conda-forge
cuda-nvcc-dev_linux-64    13.2.86              he91c749_0    conda-forge
cuda-nvcc-impl            13.2.86              h85509e4_0    conda-forge
cuda-nvcc-tools           13.2.86              he02047a_0    conda-forge
cuda-nvcc_linux-64        13.2.86              hb2fc203_0    conda-forge
cuda-nvdisasm             13.2.86              hffce074_0    conda-forge
cuda-nvml-dev             13.2.86              hffce074_0    conda-forge
cuda-nvprune              13.2.86              hffce074_0    conda-forge
cuda-nvrtc                13.2.86              hecca717_0    conda-forge
cuda-nvrtc-dev            13.2.86              hecca717_0    conda-forge
cuda-nvtx                 13.2.86              hecca717_0    conda-forge
cuda-nvtx-dev             13.2.86              ha770c72_0    conda-forge
cuda-nvvm-dev_linux-64    13.2.86              ha770c72_0    conda-forge
cuda-nvvm-impl            13.2.86              h4bc722e_0    conda-forge
cuda-nvvm-tools           13.2.86              h4bc722e_0    conda-forge
cuda-opencl               13.2.86              hecca717_0    conda-forge
cuda-opencl-dev           13.2.86              hecca717_0    conda-forge
cuda-profiler-api         13.2.86              h7938cbb_0    conda-forge
cuda-runtime              13.2.2               ha804496_0    conda-forge
cuda-sanitizer-api        13.2.87              h10ca0ad_0    conda-forge
cuda-tileiras             13.2.86              hecca717_0    conda-forge
cuda-toolkit              13.2.2               ha804496_0    conda-forge
cuda-tools                13.2.2               ha770c72_0    conda-forge
cuda-version              13.2                 he2cc418_3    conda-forge
cuda-visual-tools         13.2.2               ha770c72_0    conda-forge
cupy                      13.6.0           py39h52119e0_0    conda-forge
cupy-core                 13.6.0           py39h2678e85_0    conda-forge
cxx-compiler              2.0.0                hdab9b82_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
dbus                      1.16.2               he8c428d_2    conda-forge
debugpy                   1.8.16           py39haef64b4_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.4.0              pyhd8ed1ab_0    conda-forge
ewah-bool-utils           1.2.2            py39h3b40f6f_1    conda-forge
exceptiongroup            1.3.0              pyhd8ed1ab_0    conda-forge
executing                 2.2.0              pyhd8ed1ab_0    conda-forge
fastrlock                 0.8.3            py39hd56a1bd_1    conda-forge
fftw                      3.3.10          mpi_mpich_h084ba78_11    conda-forge
filelock                  3.19.1             pyhd8ed1ab_0    conda-forge
fmt                       12.1.0               h76c4fd7_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.18.3               h4db4eae_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                    hc364b38_1    conda-forge
fortran-compiler          2.0.0                h0f4f740_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_1    conda-forge
freetype                  2.14.3               ha770c72_2    conda-forge
gcc                       15.3.0               hc6a0c74_4    conda-forge
gcc_impl_linux-64         15.3.0               h6f13dc8_4    conda-forge
gcc_linux-64              15.3.0               h7df7c86_1    conda-forge
gdb                       16.3             py39h2837136_3    conda-forge
gds-tools                 1.17.1.22            h676940d_0    conda-forge
gfortran                  15.3.0               hc6a0c74_4    conda-forge
gfortran_impl_linux-64    15.3.0               h27ced10_4    conda-forge
git                       2.55.0          pl5321h5685339_1    conda-forge
gmp                       6.3.0                hfd2156b_3    conda-forge
gmpy2                     2.2.1            py39h7196dd7_0    conda-forge
gxx                       15.3.0               hc6a0c74_4    conda-forge
gxx_impl_linux-64         15.3.0               h90d9265_4    conda-forge
gxx_linux-64              15.3.0               h8c4937a_1    conda-forge
h11                       0.16.0             pyhd8ed1ab_0    conda-forge
h2                        4.2.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          nompi_py39h394ba53_103    conda-forge
hdf5                      1.14.4          mpi_mpich_h7f58efa_5    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
httpcore                  1.0.9              pyh29332c3_0    conda-forge
httpx                     0.28.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.11               pyhf9edf01_1    conda-forge
importlib-metadata        8.7.0              pyhe01879c_1    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_1    conda-forge
ipykernel                 6.30.1             pyh82676e8_0    conda-forge
ipympl                    0.9.7              pyhd8ed1ab_0    conda-forge
ipython                   8.18.1             pyh707e725_3    conda-forge
ipython_genutils          0.2.0              pyhd8ed1ab_2    conda-forge
ipywidgets                8.1.7              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_1    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6              pyhd8ed1ab_0    conda-forge
json5                     0.12.1             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0            py39hf3d152e_1    conda-forge
jsonschema                4.25.1             pyhe01879c_0    conda-forge
jsonschema-specifications 2025.4.1           pyh29332c3_0    conda-forge
jsonschema-with-format-nongpl 4.25.1               he01879c_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_1    conda-forge
jupyter-lsp               2.2.6              pyhe01879c_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.8.1              pyh31011fe_0    conda-forge
jupyter_events            0.12.0             pyhe01879c_0    conda-forge
jupyter_server            2.16.0             pyhe01879c_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_1    conda-forge
jupyterlab                4.4.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_2    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.15             pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   4.18.0               he073ed8_9    conda-forge
keyutils                  1.6.3                h7cc23a3_1    conda-forge
kiwisolver                1.4.7            py39h74842e3_0    conda-forge
krb5                      1.22.2               hbc21106_2    conda-forge
lapackpp                  2022.05.00           h7b070e0_0    conda-forge
lark                      1.2.2              pyhd8ed1ab_1    conda-forge
lcms2                     2.19.1               h9073bf1_2    conda-forge
ld_impl_linux-64          2.46.1          default_hbd61a6d_102    conda-forge
lerc                      4.2.0                hdb68285_0    conda-forge
libadios2                 2.10.2          mpi_mpich_h4f42236_1    conda-forge
libaec                    1.1.5                h088129d_0    conda-forge
libarchive                3.8.9           gpl_hc2c16d8_100    conda-forge
libblas                   3.11.0          10_h4a7cf45_openblas    conda-forge
libboost                  1.85.0               h0ccab89_4    conda-forge
libboost-devel            1.85.0               h00ab1b0_4    conda-forge
libboost-headers          1.85.0               ha770c72_4    conda-forge
libboost-python           1.85.0           py39h1eb36c5_4    conda-forge
libboost-python-devel     1.85.0           py39he8689d4_4    conda-forge
libcap                    2.78                 h084b8d7_1    conda-forge
libcblas                  3.11.0          10_h0358290_openblas    conda-forge
libcublas                 13.4.1.3             h676940d_0    conda-forge
libcublas-dev             13.4.1.3             h676940d_0    conda-forge
libcufft                  12.2.0.57            hecca717_0    conda-forge
libcufft-dev              12.2.0.57            hecca717_0    conda-forge
libcufile                 1.17.1.22            h85c024f_0    conda-forge
libcufile-dev             1.17.1.22            h676940d_0    conda-forge
libcuobjclient            1.1.1.22             hecca717_0    conda-forge
libcuobjclient-dev        1.1.1.22             hecca717_0    conda-forge
libcurand                 10.4.2.66            h676940d_0    conda-forge
libcurand-dev             10.4.2.66            h676940d_0    conda-forge
libcurl                   8.21.0               hcf29cc6_1    conda-forge
libcusolver               12.2.0.11            h676940d_0    conda-forge
libcusolver-dev           12.2.0.11            h676940d_0    conda-forge
libcusparse               12.7.10.12           hecca717_0    conda-forge
libcusparse-dev           12.7.10.12           hecca717_0    conda-forge
libdeflate                1.25                 hd45a770_1    conda-forge
libedit                   3.1.20250104    pl5321h373387f_1    conda-forge
libev                     4.33                 h280c20c_3    conda-forge
libexpat                  2.8.1                hecca717_1    conda-forge
libfabric                 2.6.0                ha770c72_0    conda-forge
libfabric1                2.6.0                h6b3ec72_0    conda-forge
libffi                    3.7.0                h81df57d_1    conda-forge
libfreetype               2.14.3               ha770c72_2    conda-forge
libfreetype6              2.14.3               h5e6c136_2    conda-forge
libgcc                    16.2.0               ha9f2e26_4    conda-forge
libgcc-devel_linux-64     15.3.0             h2b852eb_104    conda-forge
libgcc-ng                 16.2.0               h69a702a_4    conda-forge
libgfortran               16.2.0               h69a702a_4    conda-forge
libgfortran-ng            16.2.0               h69a702a_4    conda-forge
libgfortran5              16.2.0               h6b99dfc_4    conda-forge
libglib                   2.88.3               he503a2a_3    conda-forge
libglvnd                  1.7.0                ha4b6fd6_5    conda-forge
libgomp                   16.2.0               he0feb66_4    conda-forge
libhiredis                1.3.0                h5888daf_1    conda-forge
libhwloc                  2.12.2          default_hafda6a7_1000    conda-forge
libiconv                  1.18                 h0cb94f2_3    conda-forge
libjpeg-turbo             3.2.0                hb03c661_1    conda-forge
liblapack                 3.11.0          10_h47877c9_openblas    conda-forge
liblapacke                3.11.0          10_h6ae95b6_openblas    conda-forge
liblzma                   5.8.3                hb03c661_1    conda-forge
liblzma-devel             5.8.3                hb03c661_1    conda-forge
libmamba                  2.9.0           py313hc1bd57e_0    conda-forge
libmsgpack-c              6.1.0                h54a6638_7    conda-forge
libnghttp2                1.68.1               h74cf4be_1    conda-forge
libnl                     3.11.0               hb03c661_1    conda-forge
libnpp                    13.1.0.59            h676940d_0    conda-forge
libnpp-dev                13.1.0.59            h676940d_0    conda-forge
libnsl                    2.0.1                hb9d3cd8_1    conda-forge
libnuma                   2.0.18               hb03c661_4    conda-forge
libnvfatbin               13.2.86              hecca717_0    conda-forge
libnvfatbin-dev           13.2.86              hecca717_0    conda-forge
libnvjitlink              13.2.86              hecca717_0    conda-forge
libnvjitlink-dev          13.2.86              hecca717_0    conda-forge
libnvjpeg                 13.1.0.59            hecca717_0    conda-forge
libnvjpeg-dev             13.1.0.59            ha770c72_0    conda-forge
libnvptxcompiler-dev      13.2.86              ha770c72_0    conda-forge
libnvptxcompiler-dev_linux-64 13.2.86              ha770c72_0    conda-forge
libopenblas               0.3.34          pthreads_hcf972fe_1    conda-forge
libopengl                 1.7.0                ha4b6fd6_5    conda-forge
libpng                    1.6.58               h922cc85_1    conda-forge
libsanitizer              15.3.0               h54950a5_4    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.39               h72ddc62_1    conda-forge
libsqlite                 3.53.4               h0737f62_1    conda-forge
libssh2                   1.11.1               h6154650_1    conda-forge
libstdcxx                 16.2.0               h934c35e_4    conda-forge
libstdcxx-devel_linux-64  15.3.0             hb2c5482_104    conda-forge
libstdcxx-ng              16.2.0               hdf11a46_4    conda-forge
libsystemd0               257.13               h084b8d7_1    conda-forge
libtiff                   4.7.2                hcc2c06a_1    conda-forge
libudev1                  257.13               h084b8d7_1    conda-forge
libuuid                   2.42.3               hcfc3c73_0    conda-forge
libuv                     1.52.1               h280c20c_1    conda-forge
libwebp-base              1.6.0                hd42ef1d_1    conda-forge
libxcb                    1.17.0               hb83e432_2    conda-forge
libxcrypt                 4.4.38               h280c20c_0    conda-forge
libxkbcommon              1.13.2               h51789e4_1    conda-forge
libxkbfile                1.1.0                h166bdaf_1    conda-forge
libxml2                   2.15.1               h26afc86_0    conda-forge
libxml2-16                2.15.1               ha9997c6_0    conda-forge
libzlib                   1.3.2                h25fd6f3_3    conda-forge
lz4-c                     1.10.0               hee9eb32_2    conda-forge
lzo                       2.10              hebe6cf0_1003    conda-forge
make                      4.4.1                hb03c661_3    conda-forge
mamba                     2.9.0                h10f8075_0    conda-forge
markupsafe                3.0.2            py39h9399b63_1    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py39h98787fa_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mistune                   3.1.3              pyh29332c3_0    conda-forge
more-itertools            10.7.0             pyhd8ed1ab_0    conda-forge
mpc                       1.4.0                ha2cb11d_1    conda-forge
mpfr                      4.2.2                ha2cb11d_1    conda-forge
mpi                       1.0.1                     mpich    conda-forge
mpi4py                    4.1.0           py39h7742bde_101    conda-forge
mpich                     4.3.2              h23078de_105    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_1    conda-forge
nbclient                  0.10.4             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.6             pyh29332c3_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_1    conda-forge
ncurses                   6.6                  hdb14827_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
ninja                     1.13.2               h171cf75_1    conda-forge
nlohmann_json-abi         3.12.0               h0f90c79_2    conda-forge
notebook                  7.4.5              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_1    conda-forge
nsight-compute            2026.1.1.2           h60dd89f_0    conda-forge
nspr                      4.40                 h29cc59b_0    conda-forge
nss                       3.118                h445c969_0    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
ocl-icd                   2.3.4                hb03c661_1    conda-forge
opencl-headers            2025.06.13           hecca717_0    conda-forge
openjpeg                  2.5.4                heb1ab33_2    conda-forge
openpmd-api               0.16.1          mpi_mpich_py39hc87eab3_2    conda-forge
openpmd-viewer            1.11               pyhd8ed1ab_1    conda-forge
openssl                   3.6.4                h781a0a9_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_1    conda-forge
packaging                 26.3               pyhc364b38_0    conda-forge
pandas                    2.2.3            py39h3b40f6f_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_1    conda-forge
pcre2                     10.47                h8b3dc9c_1    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_1    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.3.0           py39h15c0740_0    conda-forge
pip                       25.2               pyh8b19718_0    conda-forge
pkg-config                0.29.2            h1114479_1013    conda-forge
platformdirs              4.3.8              pyhe01879c_0    conda-forge
pluggy                    1.6.0              pyhf9edf01_1    conda-forge
prometheus_client         0.22.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.51             pyha770c72_0    conda-forge
prompt_toolkit            3.0.51               hd8ed1ab_0    conda-forge
psutil                    7.0.0            py39h8cd3c5a_0    conda-forge
pthread-stubs             0.4               h7cc23a3_1004    conda-forge
ptyprocess                0.7.0              pyhd8ed1ab_1    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pygments                  2.19.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.2.3              pyhe01879c_2    conda-forge
pyproject_hooks           1.2.0              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
pytest                    8.4.1              pyhd8ed1ab_0    conda-forge
python                    3.9.23          hc30ae73_0_cpython    conda-forge
python-build              1.4.4              pyhc364b38_0    conda-forge
python-dateutil           2.9.0.post0        pyhe01879c_2    conda-forge
python-fastjsonschema     2.21.2             pyhe01879c_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2025.2             pyhd8ed1ab_0    conda-forge
python-wget               3.2                        py_0    conda-forge
python_abi                3.9                      9_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2            py39h9399b63_2    conda-forge
pyzmq                     26.2.0           py39h4e4fb57_1    conda-forge
rdma-core                 65.0                 h7b4f2e6_0    conda-forge
readline                  8.3                  hd6e31c0_1    conda-forge
referencing               0.36.2             pyh29332c3_0    conda-forge
reproc                    14.2.8.post0         hee9eb32_0    conda-forge
reproc-cpp                14.2.8.post0         h1c70be6_0    conda-forge
requests                  2.32.5             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_1    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rfc3987-syntax            1.1.0              pyhe01879c_1    conda-forge
rhash                     1.4.6                hb03c661_2    conda-forge
rpds-py                   0.27.0           py39h17f49b6_0    conda-forge
scipy                     1.13.1           py39haf93ffa_0    conda-forge
send2trash                1.8.3              pyh0d859eb_1    conda-forge
setuptools                80.9.0             pyhff2d567_0    conda-forge
simdjson                  4.6.11               h4dbf13b_0    conda-forge
six                       1.17.0             pyhe01879c_1    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_1    conda-forge
soupsieve                 2.7                pyhd8ed1ab_0    conda-forge
spdlog                    1.17.0               hb6aa676_2    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
sympy                     1.14.0           pyh2585a3b_105    conda-forge
sysroot_linux-64          2.28                 h4ee821c_9    conda-forge
terminado                 0.18.1             pyh0d859eb_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h1df4ec4_4    conda-forge
tomli                     2.2.1              pyhe01879c_2    conda-forge
tomli-w                   1.2.0              pyhd8ed1ab_0    conda-forge
tornado                   6.5.2            py39hd399759_0    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
types-python-dateutil     2.9.0.20250809     pyhd8ed1ab_0    conda-forge
typing-extensions         4.14.1               h4440ef1_0    conda-forge
typing_extensions         4.14.1             pyhe01879c_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_1    conda-forge
tzdata                    2026c                h151e31d_0    conda-forge
ucx                       1.20.1               hf72d326_0    conda-forge
unyt                      3.0.4              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_1    conda-forge
urllib3                   2.5.0              pyhd8ed1ab_0    conda-forge
virtualenv                20.34.0            pyhd8ed1ab_0    conda-forge
wayland                   1.26.0               hc1c935e_2    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
webcolors                 24.11.1            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_3    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.14             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.1                h4f16b4b_2    conda-forge
xcb-util-cursor           0.1.6                hb03c661_0    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xkeyboard-config          2.48                 h280c20c_0    conda-forge
xorg-libice               1.1.2                h280c20c_0    conda-forge
xorg-libsm                1.2.6                h0d788c3_1    conda-forge
xorg-libx11               1.8.13               he1eb515_1    conda-forge
xorg-libxau               1.0.12               hb03c661_2    conda-forge
xorg-libxcomposite        0.4.7                hb03c661_0    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb03c661_2    conda-forge
xorg-libxext              1.3.7                h7cc23a3_1    conda-forge
xorg-libxfixes            6.0.2                h7cc23a3_1    conda-forge
xorg-libxi                1.8.3                h7cc23a3_1    conda-forge
xorg-libxrandr            1.5.5                h7cc23a3_1    conda-forge
xorg-libxrender           0.9.12               hb03c661_1    conda-forge
xorg-libxtst              1.2.5                h7cc23a3_4    conda-forge
xxhash                    0.8.3                hec8ed23_1    conda-forge
xz                        5.8.3                ha02ee65_1    conda-forge
xz-gpl-tools              5.8.3                ha02ee65_1    conda-forge
xz-tools                  5.8.3                hb03c661_1    conda-forge
yaml                      0.2.5                hebe6cf0_3    conda-forge
yaml-cpp                  0.8.0                h54a6638_1    conda-forge
yt                        4.3.1            py39h3b40f6f_2    conda-forge
zeromq                    4.3.5                h59595ed_1    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.2                h25fd6f3_3    conda-forge
zlib-ng                   2.2.5                hde8ca8f_1    conda-forge
zstandard                 0.23.0           py39hd399759_3    conda-forge
zstd                      1.5.7                hb78ec9c_7    conda-forge
```

- Computational resources:
  - [X] CPU: AMD EPYC3 7643
  - [X] GPU: Nvidia A40

If applicable, please add any additional information about your software environment:
- [X] CMake: 4.4.3
- [X] C++ compiler: GNU 15.3 with NVCC 13.2.86
- [X] Python: CPython 3.9.23
- [X] MPI: MPICH 4.3.2
- [X] FFTW: 3.3.10
- [X] HDF5: 1.14.4
- [ ] ADIOS2

## Output of configuration and build:
- stdout:
[stdout.txt](https://github.com/user-attachments/files/32010660/stdout.txt)

- stderr
[stderr.txt](https://github.com/user-attachments/files/32010659/stderr.txt)

**Comment by ax3l** [comment]
Hi @plasmahomie (btw, nice username!),

Welcome to WarpX!

Unfortunately, Conda-Forge packages for LAPACK++/BLAS++ are build CPU-only, so you cannot use them for CUDA builds.

You will need to compile them manually, e.g., similar to this:
https://github.com/BLAST-WarpX/warpx/blob/92258c4bd83d548e1aa72651dfd4643b65aa1102/Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh#L104-L132

But independent of that we need to bring the conda-forge packages to the latest version.

**Comment by plasmahomie** [comment]
Hi, thanks for the response. Sorry I meant to add a comment earlier but forgot - I already actually got WarpX set up and installed with BLAS++ and LAPACK++ built from source. I ran into another problem later that the version of boost on conda-forge requires python version 3.9 (I think? maybe it was 3.8) as well, which is too low for the pywarpx install. Maybe it works ok anyway, but during the compilation it complained about incorrect version so I just made a new environment without boost and compiled with WarpX_QED_TABLE_GEN=OFF instead.

So both lapackpp and boost on conda-forge need updated! And maybe in the meantime a note on the docs about this would be helpful?

**Comment by ax3l** [comment]
Hi @plasmahomie,

we just merged a new conda-forge version of LAPACK++ https://github.com/conda-forge/lapackpp-feedstock/pull/7

In a few hours, when the package is fully published, can you please try creating a brand new, fresh conda environment? It will pull then latest LAPACK++ package automatically and you can try again if it works without you needing to compile BLAS++/LAPACK++ 🤞 

> I ran into another problem later that the version of boost on conda-forge requires python version 3.9 (I think? maybe it was 3.8) as well, which is too low for the pywarpx install

That is a confusing problem and an ancient Python. We could try to replace the `boost` package with `libboost-devel` to avoid pulling `libboost-python`, which we do not use... Anyway, I tried reproducing the old Python and do not see the same issue:

<img width="2087" height="444" alt="Image" src="https://github.com/user-attachments/assets/677dacbb-5f79-46a5-a8f7-492d9c0cd7ef" />

So maybe it is worth updating your conda/mamba base install and the resolver might just be a bit dated?
